// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: LabGRPC1.proto

// Protobuf Java Version: 3.25.2
package MyLab1;

public interface HelloRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:MyLab1.HelloRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string greeting = 1;</code>
   * @return The greeting.
   */
  java.lang.String getGreeting();
  /**
   * <code>string greeting = 1;</code>
   * @return The bytes for greeting.
   */
  com.google.protobuf.ByteString
      getGreetingBytes();
}
