// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: LabGRPC1.proto

// Protobuf Java Version: 3.25.2
package MyLab1;

public final class LabGRPC1 {
  private LabGRPC1() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_MyLab1_HelloRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_MyLab1_HelloRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_MyLab1_HelloResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_MyLab1_HelloResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016LabGRPC1.proto\022\006MyLab1\" \n\014HelloRequest" +
      "\022\020\n\010greeting\030\001 \001(\t\"\036\n\rHelloResponse\022\r\n\005r" +
      "eply\030\001 \001(\t2G\n\014HelloService\0227\n\010SayHello\022\024" +
      ".MyLab1.HelloRequest\032\025.MyLab1.HelloRespo" +
      "nseB\002P\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_MyLab1_HelloRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_MyLab1_HelloRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_MyLab1_HelloRequest_descriptor,
        new java.lang.String[] { "Greeting", });
    internal_static_MyLab1_HelloResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_MyLab1_HelloResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_MyLab1_HelloResponse_descriptor,
        new java.lang.String[] { "Reply", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
