// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Ex0.proto

// Protobuf Java Version: 3.25.2
package td0;

public final class Ex0 {
  private Ex0() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_td0_MyUser_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_td0_MyUser_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\tEx0.proto\022\003td0\".\n\006MyUser\022\r\n\005email\030\001 \001(" +
      "\t\022\025\n\ryear_of_birth\030\002 \001(\rB\002P\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_td0_MyUser_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_td0_MyUser_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_td0_MyUser_descriptor,
        new java.lang.String[] { "Email", "YearOfBirth", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
